// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().optional(),
    OPEN_AI_API_KEY: z.number({ coerce: true }).min(1),
    MINIMUM_DAYS: z.number({ coerce: true }).default(1).optional(),
    MINIMUM_MEMBERS: z.number({ coerce: true }).min(1).default(10),
    MINIMUM_HEADS: z.number({ coerce: true }).min(1).default(0),
  },
  client: {
    NEXT_PUBLIC_PUBLISHABLE_KEY: z.string().optional(),
    NEXT_PUBLIC_MAXIMUM_HEADS: z.number({ coerce: true }).min(1).default(0),
    NEXT_PUBLIC_MAXIMUM_DAYS: z.number({ coerce: true }).min(1).default(10),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_PUBLISHABLE_KEY,
    NEXT_PUBLIC_MAXIMUM_HEADS: process.env.NEXT_PUBLIC_MAXIMUM_HEADS,
    NEXT_PUBLIC_MAXIMUM_DAYS: process.env.NEXT_PUBLIC_MAXIMUM_DAYS,
  }
});
